---
- hosts: all
  gather_facts: false
  tasks:
    - name: update sysctl ipv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
    - name: add iptables masquerade
      shell: iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE


