---
- hosts: all
  gather_facts: false
  tasks:
    - name: delete sysctl ipv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        sysctl_set: yes
        state: present
        reload: yes
    - name: remove iptables masquerade
      shell: iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE


